package org.strum;

import static java.util.Collections.singleton;
import static java.util.stream.Stream.concat;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.util.Collection;
import java.util.stream.Stream;

import org.strum.node.IONode;
import org.strum.node.IntrinsicNode;
import org.strum.node.SideEffectNode;
import org.strum.node.StrumNode;

import com.oracle.truffle.api.CallTarget;
import com.oracle.truffle.api.CompilerDirectives;
import com.oracle.truffle.api.CompilerDirectives.TruffleBoundary;
import com.oracle.truffle.api.Scope;
import com.oracle.truffle.api.Truffle;
import com.oracle.truffle.api.TruffleLanguage;
import com.oracle.truffle.api.TruffleLanguage.Env;
import com.oracle.truffle.api.dsl.NodeFactory;
import com.oracle.truffle.api.frame.FrameDescriptor;
import com.oracle.truffle.api.instrumentation.AllocationReporter;
import com.oracle.truffle.api.interop.TruffleObject;
import com.oracle.truffle.api.nodes.NodeInfo;
import com.oracle.truffle.api.object.DynamicObject;
import com.oracle.truffle.api.object.Shape;
import com.oracle.truffle.api.source.Source;

public class StrumContext {
  private static final Source BUILTIN_SOURCE = Source
      .newBuilder(StrumLanguage.ID, "", "SL builtin")
      .build();

  private final Env env;
  private final BufferedReader input;
  private final PrintWriter output;
  private final StrumDefinitionRegistry functionRegistry;
  private final StrumLanguage language;
  private final AllocationReporter allocationReporter;
  private final Iterable<Scope> topScopes; // Cache the top scopes

  public StrumContext(
      StrumLanguage language,
      TruffleLanguage.Env env,
      Collection<? extends NodeFactory<? extends IntrinsicNode>> externalIntrinsics,
      Collection<? extends NodeFactory<? extends IONode>> externalSideEffects) {
    this.env = env;
    this.input = new BufferedReader(new InputStreamReader(env.in()));
    this.output = new PrintWriter(env.out(), true);
    this.language = language;
    this.allocationReporter = env.lookup(AllocationReporter.class);
    this.functionRegistry = new StrumDefinitionRegistry(language);
    this.topScopes = singleton(
        Scope.newBuilder("global", functionRegistry.getFunctionsObject()).build());

    concat(getIntrinsics(), externalIntrinsics.stream()).forEach(this::installIntrinsic);
    concat(getSideEffects(), externalSideEffects.stream()).forEach(this::installSideEffect);
  }

  /**
   * Return the current Truffle environment.
   */
  public Env getEnv() {
    return env;
  }

  /**
   * Returns the default input, i.e., the source for the {@link SLReadlnBuiltin}.
   * To allow unit testing, we do not use {@link System#in} directly.
   */
  public BufferedReader getInput() {
    return input;
  }

  /**
   * The default default, i.e., the output for the {@link SLPrintlnBuiltin}. To
   * allow unit testing, we do not use {@link System#out} directly.
   */
  public PrintWriter getOutput() {
    return output;
  }

  /**
   * Returns the registry of all functions that are currently defined.
   */
  public SLFunctionRegistry getFunctionRegistry() {
    return functionRegistry;
  }

  public Iterable<Scope> getTopScopes() {
    return topScopes;
  }

  /**
   * Add all our intrinsic function implementations to the root scope. Note that
   * there are very few "built-in" functions so to speak; almost all functions
   * have in-language implementations. But for performance reasons some core
   * functionality does need to be transparently lifted into intrinsics.
   * <P>
   * This is also important for bootstrapping macro facilities, since the
   * implementation does not aim to be meta-circulat/self-hosting.
   */
  private Stream<NodeFactory<? extends IntrinsicNode>> getIntrinsics() {
    Stream
        .of(
            SLReadlnBuiltinFactory.getInstance(),
            SLPrintlnBuiltinFactory.getInstance(),
            SLNanoTimeBuiltinFactory.getInstance(),
            SLDefineFunctionBuiltinFactory.getInstance(),
            SLStackTraceBuiltinFactory.getInstance(),
            SLHelloEqualsWorldBuiltinFactory.getInstance(),
            SLNewObjectBuiltinFactory.getInstance(),
            SLEvalBuiltinFactory.getInstance(),
            SLImportBuiltinFactory.getInstance(),
            SLGetSizeBuiltinFactory.getInstance(),
            SLHasSizeBuiltinFactory.getInstance(),
            SLIsExecutableBuiltinFactory.getInstance(),
            SLIsNullBuiltinFactory.getInstance(),
            SLWrapPrimitiveBuiltinFactory.getInstance());
  }

  public void installIntrinsic(NodeFactory<? extends IntrinsicNode> factory) {
    /*
     * The builtin node factory is a class that is automatically generated by the
     * Truffle DSL. The signature returned by the factory reflects the signature of
     * the @Specialization
     *
     * methods in the builtin classes.
     */
    int argumentCount = factory.getExecutionSignature().size();
    StrumNode[] argumentNodes = new StrumNode[argumentCount];
    /*
     * Builtin functions are like normal functions, i.e., the arguments are passed
     * in as an Object[] array encapsulated in SLArguments. A SLReadArgumentNode
     * extracts a parameter from this array.
     */
    for (int i = 0; i < argumentCount; i++) {
      argumentNodes[i] = new SLReadArgumentNode(i);
    }
    /* Instantiate the builtin node. This node performs the actual functionality. */
    SLBuiltinNode builtinBodyNode = factory.createNode((Object) argumentNodes);
    builtinBodyNode.addRootTag();
    /*
     * The name of the builtin function is specified via an annotation on the node
     * class.
     */
    String name = lookupNodeInfo(builtinBodyNode.getClass()).shortName();
    builtinBodyNode.setUnavailableSourceSection();

    /*
     * Wrap the builtin in a RootNode. Truffle requires all AST to start with a
     * RootNode.
     */
    SLRootNode rootNode = new SLRootNode(
        language,
        new FrameDescriptor(),
        builtinBodyNode,
        BUILTIN_SOURCE.createUnavailableSection(),
        name);

    /* Register the builtin function in our function registry. */
    getFunctionRegistry().register(name, Truffle.getRuntime().createCallTarget(rootNode));
  }

  private Stream<NodeFactory<? extends IONode>> getSideEffects() {
    // TODO
    throw new UnsupportedOperationException();
  }

  public void installSideEffect(NodeFactory<? extends IONode> factory) {
    // TODO
    throw new UnsupportedOperationException();
  }

  public static NodeInfo lookupNodeInfo(Class<?> clazz) {
    if (clazz == null) {
      return null;
    }
    NodeInfo info = clazz.getAnnotation(NodeInfo.class);
    if (info != null) {
      return info;
    } else {
      return lookupNodeInfo(clazz.getSuperclass());
    }
  }

  /*
   * Methods for object creation / object property access.
   */
  public AllocationReporter getAllocationReporter() {
    return allocationReporter;
  }

  /**
   * Allocate an empty object. All new objects initially have no properties.
   * Properties are added when they are first stored, i.e., the store triggers a
   * shape change of the object.
   */
  public DynamicObject createObject(AllocationReporter reporter) {
    DynamicObject object = null;
    reporter.onEnter(null, 0, AllocationReporter.SIZE_UNKNOWN);
    object = emptyShape.newInstance();
    reporter.onReturnValue(object, 0, AllocationReporter.SIZE_UNKNOWN);
    return object;
  }

  public static boolean isStrumObject(Object value) {
    /*
     * 
     * 
     * TODO for strum do we need to have some kind of warmed up ConsLibrary here?
     * 
     * 
     * 
     * 
     * 
     * LAYOUT.getType() returns a concrete implementation class, i.e., a class that
     * is more precise than the base class DynamicObject. This makes the type check
     * faster.
     */
    return LAYOUT.getType().isInstance(value)
        && LAYOUT.getType().cast(value).getShape().getObjectType() == StrumObjectType.SINGLETON;
  }

  /*
   * Methods for language interoperability.
   */

  public static Object fromForeignValue(Object a) {
    if (a instanceof Long || a instanceof String || a instanceof Boolean) {
      return a;
    } else if (a instanceof Character) {
      return String.valueOf(a);
    } else if (a instanceof Number) {
      return fromForeignNumber(a);
    } else if (a instanceof TruffleObject) {
      return a;
    } else if (a instanceof StrumContext) {
      return a;
    }
    CompilerDirectives.transferToInterpreter();
    throw new IllegalStateException(a + " is not a Truffle value");
  }

  @TruffleBoundary
  private static long fromForeignNumber(Object a) {
    return ((Number) a).longValue();
  }

  public CallTarget parse(Source source) {
    return env.parsePublic(source);
  }

  /**
   * Returns an object that contains bindings that were exported across all used
   * languages. To read or write from this object the {@link TruffleObject
   * interop} API can be used.
   */
  public TruffleObject getPolyglotBindings() {
    return (TruffleObject) env.getPolyglotBindings();
  }

  public static StrumContext getCurrent() {
    return StrumLanguage.getCurrentContext();
  }
}